language: php

dist: trusty

php:
  - 7.2

services:
  - mysql

env:
  global:
    - DEFAULT=1
    - DATABASE_TEST_URL=mysql://travis@127.0.0.1/test_blog?encoding=utf8mb4&timezone=UTC&cacheMetadata=true

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=1

    - php: 7.2
      env: PHPSTAN=1 DEFAULT=1

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_blog;'

before_script:
  - if [[ $DEFAULT = 1 ]]; then composer install; fi
  - if [[ $DEFAULT = 1 ]]; then composer run-script post-install-cmd --no-interaction; fi

script:
  - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 5 src/; fi

notifications:
  email: false
